schema_version: 20180708
name: quotation
version: 0.0.11
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.72
run_image: fnproject/fn-java-fdk:jdk9-1.0.72
cmd: org.paumard.oc2018.quotation.Quotation::quote
format: http-stream
triggers:
- name: quotation
  type: http
  source: /quotation
