schema_version: 20180708
name: weatherforecast
version: 0.0.8
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.72
run_image: fnproject/fn-java-fdk:jdk9-1.0.72
cmd: org.paumard.oc2018.weather.WeatherForecast::forecast
format: http-stream
triggers:
- name: weatherforecast
  type: http
  source: /weatherforecast
